<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>


<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ, осень 2021</b></h3>

## Домашнее задание: библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем функцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
# a = np.random.sample((100, 100))
# b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# print(a.ndim, a.shape)
# print(b.ndim, b.shape)
# print(a)
# print(b)

In [3]:
M,N = 100,100
matrix_a = [[random.random() for y in range(M)] for x in range(N)]
matrix_b = [[random.random() for y in range(M)] for x in range(N)]

In [4]:
def mult(a, b):
	"""  
	a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
	b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
	return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

	Функция принимает на вход две матрицы: a и b размерностью size x size
	Возвращает матрицу их произведения a * b = c 

	Реализуйте умножение матриц без использования функций из пакета numpy
	"""
	rows_A = len(a)
	cols_A = len(a[0])
	cols_B = len(b[0])
	C = [[0 for row in range(cols_B)] for col in range(rows_A)]
	for i in range(rows_A):
		for j in range(cols_B):
			for k in range(cols_A):
				C[i][j] += a[i][k] * b[k][j]
	return C

In [5]:
def np_mult(a, b):
	"""  
	a: np.array[size, size]             --- первая матрица-аргумент
	b: np.array[size, size] --- вторая матрица-аргумент
	return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

	Функция принимает на вход две матрицы: a и b размерностью size x size
	Возвращает матрицу их произведения a * b = c 

	Реализуйте умножение матриц, используя функции из пакета numpy
	"""
	c = a.dot(b) # a @ b
	return c

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(matrix_a, matrix_b)
len(M1)

CPU times: user 89.7 ms, sys: 1.08 ms, total: 90.7 ms
Wall time: 90 ms


100

In [7]:
a = np.array(matrix_a)
b = np.array(matrix_b)

In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
M2.shape

CPU times: user 50.2 ms, sys: 38.5 ms, total: 88.7 ms
Wall time: 14.6 ms


(100, 100)

In [9]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
# a = np.random.sample((1, 3))
# a = list(a)[0]
# b = np.random.sample((1, 3))
# b = list(b)[0]
# print(a, b)

In [11]:
a = [random.random() for y in range(3)]
b = [random.random() for y in range(3)]

In [12]:
def scalar_product(a, b):
	"""  
	a: lists of 3 ints --- первая матрица-аргумент длиной n
	b: lists of 3 ints --- вторая матрица-аргумент длиной n
	return c: float  --- результат скалярного произведения векторов a и b

	Функция принимает на вход два вектора длиной n
	Возвращает число, равное их скалярному произведению a x b = c 

	Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

	""" 
	result = sum([i * j for i, j in zip(a, b)])
	return result

In [13]:
def np_scalar_product(a,b):
	"""  
	a: np.array[, n] --- первая матрица-аргумент
	b: np.array[, n] --- вторая матрица-аргумент
	return c: float  --- результат скалярного произведения векторов a и b

	Функция принимает на вход два вектора длиной n
	Возвращает число, равное их скалярному произведению a x b = c 

	Реализуйте скалярное умножение векторов, используя функции из пакета numpy
	""" 
	result = np.sum(a @ b)
	return result

In [14]:
%time
product_1 = scalar_product(a,b)

CPU times: user 1 µs, sys: 0 ns, total: 1 µs
Wall time: 1.91 µs


In [15]:
a = np.array(a)
b = np.array(b)

In [16]:
%time
product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 1 µs, sys: 0 ns, total: 1 µs
Wall time: 3.1 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [17]:
matr = np.diag(np.arange(3, 15, 3))
print(matr)

[[ 3  0  0  0]
 [ 0  6  0  0]
 [ 0  0  9  0]
 [ 0  0  0 12]]


In [18]:
diag = np.diagonal(matr, offset=0, axis1=0, axis2=1)
sum(diag[diag % 2 == 0])

18

In [19]:
def np_diag_2k(a):
	"""  
	a: np.array[m, m] --- первая матрица-аргумент
	return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

	Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
	равное сумме четных диагональных элементов этой квадратной матрицы

	В реализации этой функции необходимо использовать функционал пакета numpy

	""" 
	diag = np.diagonal(a, offset=0, axis1=0, axis2=1)
	result = sum(diag[diag % 2 == 0])
	return result

In [20]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 1, 7, 3, 5],
       [2, 1, 1, 2, 1],
       [2, 1, 5, 1, 6],
       [3, 1, 9, 3, 5],
       [7, 8, 9, 8, 7]])

In [21]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 32 µs, sys: 1 µs, total: 33 µs
Wall time: 33.1 µs


0

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​ 

In [22]:
def cumsum(A):
    """  
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает 
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность 
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    result = np.cumsum(A,axis=1) 
    return result

In [23]:
# зададим некоторую последовательность и проверим ее на вашей функции. 
A = sps.uniform.rvs(size=10**3).reshape(10,100)

%time
S2 = cumsum(A)

CPU times: user 0 ns, sys: 1e+03 ns, total: 1e+03 ns
Wall time: 2.15 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [24]:
rng = np.random.default_rng()
X = rng.integers(100, size=(3, 6))
X

array([[48,  9, 40, 60, 98, 74],
       [12, 12, 96, 50,  3, 25],
       [31, 82, 29, 75, 42, 28]])

In [25]:
from copy import copy
def np_transformation(X, a=1):
	"""  
	X: np.array[num_row, num_column]          --- матрица-аргумент
	a: float                                  --- значение для преобразования нечетных элементов строк в X
	return S: np.array[num_row, num_column*2] --- матрица, где строки являются 
	сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

	Функция принимает на вход матрицу X размерностью n x m, число a и 
	возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
	i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке, 
	где преобразование для числа k определено как:
	transformation(k) = a if ind(k) % 2 == 0 else k**3

	В реализации этой функции необходимо использовать функционал пакета numpy

	""" 
	arr = X.copy()
	arr[:, 1::2] = a
	arr[:, 0::2] = arr[:, 0::2]**3
	arr = arr[:, ::-1]
	result = np.hstack((X,arr))
	return result

In [26]:
X = np.array([[i for i in range(1, 10, 2)]])
print("X:", X)
%time S2 = np_transformation(X, 5)

X: [[1 3 5 7 9]]
CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 36 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд идущие повторения элементов функция сжимает в один элемент и считает количество повторений этого элемента. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [33]:
def np_encode(a):
    """  
    a: np.array[, n] --- вектор-аргумент длиной n
    return (elems, repetitions): (np.array, np.array) --- выходной кортеж из вектора 
    элементов и вектора их количеств в подряд идущих повторениях

    Функция принимает на вход вектор a длиной n, добавляет в вектор elem сжатые 
    в один элемент подряд идущие повторения элементов входного вектора a, в вектор 
    repetitions добавляет длины последовательностей подряд идущих повторений. 
    Затем функция возвращает кортеж векторов (elems, repetitions).

    В реализации этой функции необходимо использовать функционал пакета numpy

    """ 
    n = len(a)
    y = a[1:] != a[:-1]
    i = np.append(np.where(y), n - 1)
    z = np.diff(np.append(-1, i))
    return a[i], z

In [34]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [35]:
%time
x, num = np_encode(X)

CPU times: user 1e+03 ns, sys: 1e+03 ns, total: 2 µs
Wall time: 1.67 µs


In [36]:
def encode(a):
    #YOUR CODE

    Anew=np.array(list(a[-1:])+list(a[:-1]))
    elts = a[Anew != a]
    nonzero = np.nonzero(Anew != a)[0]
    repeats = np.diff(np.append(nonzero,a.size))
    return (elts,repeats)
%time
x, num = encode(X)

CPU times: user 1 µs, sys: 1e+03 ns, total: 2 µs
Wall time: 2.86 µs
